apiVersion: v1
kind: Service
metadata:
  name: order-purchasing-service
spec:
  selector:
    app: order-purchasing-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
