apiVersion: v1
kind: Service
metadata:
  name: restaurant-menu-service
spec:
  selector:
    app: restaurant-menu-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004