services:
  gateway:
    build: ./gateway
    container_name: gateway
    networks:
      - micronetwork
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - ORDER_SERVICE_URL=http://order-purchasing-service:3002
      - DELIVERY_SERVICE_URL=http://delivery-service:3003
      - RESTAURANT_MENU_SERVICE_URL=http://restaurant-menu-service:3004
      - NOTIFICATION_SERVICE_URL=http://notification-service:5001
      - PAYMENT_SERVICE_URL=http://payment-service:5002

    depends_on:
      - user-service
      - order-purchasing-service
      - delivery-service
      - restaurant-menu-service
      - notification-service
      - payment-service
      - rabbitmq
    restart: unless-stopped

  user-service:
    build: ./user-service
    container_name: user-service
    networks:
      - micronetwork
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  order-purchasing-service:
    build: ./order-purchasing-service
    container_name: order-purchasing-service
    networks:
      - micronetwork
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    networks:
      - micronetwork
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  restaurant-menu-service:
    build: ./restaurant-menu-service
    container_name: restaurant-menu-service
    networks:
      - micronetwork
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    restart: unless-stopped

  notification-service:
    build: ./notification-service
    container_name: notification-service
    networks:
      - micronetwork
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  payment-service:
    build: ./payment-service
    container_name: payment-service
    networks:
      - micronetwork
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    networks:
      - micronetwork
    ports:
      - "5672:5672" # RabbitMQ Broker Port
      - "15672:15672" # RabbitMQ Management UI
    restart: unless-stopped

networks:
  micronetwork:
    driver: bridge
