apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery-feedback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: food-delivery-feedback
  template:
    metadata:
      labels:
        app: food-delivery-feedback
    spec:
      containers:
        - name: food-delivery-feedback-service
          image: inupa/food-delivery-feedback-service:latest
          ports:
            - containerPort: 5003