apiVersion: apps/v1
kind: Service
metadata:
  name: food-delivery-feedback
spec:
  selector:
    app: food-delivery-feedback
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003